package pl.nask.crs.payment.dao.ibatis.objects;

import pl.nask.crs.payment.OperationType;
import pl.nask.crs.payment.PaymentMethod;

import java.util.Date;
import java.util.List;

/**
 * (C) Copyright 2012 NASK
 * Software Research & Development Department
 */
public class InternalTransaction {
    //generated by db
    private long id;
    private String nicHandleId;
    private Integer invoiceId;
    private String orderId;
    private boolean settlementStarted;
    private boolean settlementEnded;
    private Integer totalCost;
    private Integer totalNetAmount;
    private Integer totalVatAmount;
    private boolean cancelled;
    private Date cancelledDate;
    private Date financiallyPassedDate;
    private List<InternalReservation> reservations;
    private boolean invalidated;
    private Date invalidatedDate;
    private Long reauthorisedId;

    private Date settlementDate;
    private PaymentMethod paymentMethod;
    private OperationType operationType;
    
    //Credit card specific data
    private String realexAuthcode;
    private String realexPassref;
	private String invoiceNumber;

    public InternalTransaction() {}

    public InternalTransaction(long id, String nicHandleId, Integer invoiceId, String orderId, boolean settlementStarted, boolean settlementEnded, Integer totalCost, Integer totalNetAmount, Integer totalVatAmount, boolean cancelled, Date cancelledDate, Date financiallyPassedDate, List<InternalReservation> reservations, boolean invalidated, Date invalidatedDate, Long reauthorisedId, Date settlementDate, PaymentMethod paymentMethod, OperationType operationType, String realexAuthCode, String realexPassRef) {
        this.id = id;
        this.nicHandleId = nicHandleId;
        this.invoiceId = invoiceId;
        this.orderId = orderId;
        this.settlementStarted = settlementStarted;
        this.settlementEnded = settlementEnded;
        this.totalCost = totalCost;
        this.totalNetAmount = totalNetAmount;
        this.totalVatAmount = totalVatAmount;
        this.cancelled = cancelled;
        this.cancelledDate = cancelledDate;
        this.financiallyPassedDate = financiallyPassedDate;
        this.reservations = reservations;
        this.invalidated = invalidated;
        this.invalidatedDate = invalidatedDate;
        this.reauthorisedId = reauthorisedId;
        this.settlementDate = settlementDate;
        this.paymentMethod = paymentMethod;
        this.operationType = operationType;
        this.realexAuthcode = realexAuthCode;
        this.realexPassref = realexPassRef;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getNicHandleId() {
        return nicHandleId;
    }

    public void setNicHandleId(String nicHandleId) {
        this.nicHandleId = nicHandleId;
    }

    public Integer getInvoiceId() {
        return invoiceId;
    }

    public void setInvoiceId(Integer invoiceId) {
        this.invoiceId = invoiceId;
    }

    public String getOrderId() {
        return orderId;
    }

    public void setOrderId(String orderId) {
        this.orderId = orderId;
    }

    public boolean isSettlementStarted() {
        return settlementStarted;
    }

    public void setSettlementStarted(boolean settlementStarted) {
        this.settlementStarted = settlementStarted;
    }

    public boolean isSettlementEnded() {
        return settlementEnded;
    }

    public void setSettlementEnded(boolean settlementEnded) {
        this.settlementEnded = settlementEnded;
    }

    public Integer getTotalCost() {
        return totalCost;
    }

    public void setTotalCost(Integer totalCost) {
        this.totalCost = totalCost;
    }

    public Integer getTotalNetAmount() {
        return totalNetAmount;
    }

    public void setTotalNetAmount(Integer totalNetAmount) {
        this.totalNetAmount = totalNetAmount;
    }

    public Integer getTotalVatAmount() {
        return totalVatAmount;
    }

    public void setTotalVatAmount(Integer totalVatAmount) {
        this.totalVatAmount = totalVatAmount;
    }

    public boolean isCancelled() {
        return cancelled;
    }

    public void setCancelled(boolean cancelled) {
        this.cancelled = cancelled;
    }

    public Date getCancelledDate() {
        return cancelledDate;
    }

    public void setCancelledDate(Date cancelledDate) {
        this.cancelledDate = cancelledDate;
    }

    public Date getFinanciallyPassedDate() {
        return financiallyPassedDate;
    }

    public void setFinanciallyPassedDate(Date financiallyPassedDate) {
        this.financiallyPassedDate = financiallyPassedDate;
    }

    public List<InternalReservation> getReservations() {
        return reservations;
    }

    public void setReservations(List<InternalReservation> reservations) {
        this.reservations = reservations;
    }

    public boolean isInvalidated() {
        return invalidated;
    }

    public void setInvalidated(boolean invalidated) {
        this.invalidated = invalidated;
    }

    public Date getInvalidatedDate() {
        return invalidatedDate;
    }

    public void setInvalidatedDate(Date invalidatedDate) {
        this.invalidatedDate = invalidatedDate;
    }

    public Long getReauthorisedId() {
        return reauthorisedId;
    }

    public void setReauthorisedId(Long reauthorisedId) {
        this.reauthorisedId = reauthorisedId;
    }

    public Date getSettlementDate() {
        return settlementDate;
    }

    public void setSettlementDate(Date settlementDate) {
        this.settlementDate = settlementDate;
    }

    public PaymentMethod getPaymentMethod() {
        return paymentMethod;
    }

    public void setPaymentMethod(PaymentMethod paymentMethod) {
        this.paymentMethod = paymentMethod;
    }

    public OperationType getOperationType() {
        return operationType;
    }

    public void setOperationType(OperationType operationType) {
        this.operationType = operationType;
    }

	public String getRealexAuthcode() {
		return realexAuthcode;
	}

	public void setRealexAuthcode(String realexAuthcode) {
		this.realexAuthcode = realexAuthcode;
	}

	public String getRealexPassref() {
		return realexPassref;
	}

	public void setRealexPassref(String realexPassref) {
		this.realexPassref = realexPassref;
	}

	public String getInvoiceNumber() {
		return invoiceNumber;
	}
	
	public void setInvoiceNumber(String invoiceNumber) {
		this.invoiceNumber = invoiceNumber;
	}
}
