package pl.nask.crs.payment;

import java.math.BigDecimal;
import java.util.Date;

import pl.nask.crs.vat.PriceWithVat;

/**
 * (C) Copyright 2012 NASK
 * Software Research & Development Department
 */
public class Reservation {

    private final long id;
    private final String nicHandleId;
    private final String domainName;
    private final int durationMonths;
    private final Date creationDate;
    private final PriceWithVat priceWithVat;
    private boolean readyForSettlement;
    private boolean settled;
    private Date settledDate;
    private final Long ticketId;
    private final Long transactionId;
    private final OperationType operationType;
    // reservation period == period for which the domain is being paid for
    private Date startDate;
    private Date endDate;
    private final PaymentMethod paymentMethod;
    private Date renewalDate; // domain renewal date - must be the real renewal date of the domain, to be set after DSM events which update the domain's renewal date are fired.
    /**
     * Probably not in use any more!
     * 
     * @deprecated
     */
    private String invoiceNumber;

    private String orderId;
    private Integer ticketFinancialStatus;
    private boolean domainExists;

    public static Reservation newInstanceForTicket(String nicHandleId, String domainName, int durationMonths, PriceWithVat priceWithVat, Long ticketId, Long transactionId, OperationType operationType, PaymentMethod paymentMethod) {
        return new Reservation(-1, nicHandleId, domainName, durationMonths, new Date(), priceWithVat, false ,false, null, ticketId, transactionId, operationType, paymentMethod, null, null, null, false);
    }

    public static Reservation newInstanceForGIBORegistration(String nicHandleId, String domainName, PriceWithVat priceWithVat, long transactionId, PaymentMethod paymentMethod) {
        return new Reservation(-1, nicHandleId, domainName, 0, new Date(), priceWithVat, false, false, null, null, transactionId, OperationType.REGISTRATION, paymentMethod, null, null, null, false);
    }

    public static Reservation newInstanceForRenewal(String nicHandleId, String domainName, int durationMonths, PriceWithVat priceWithVat, long transactionId, PaymentMethod paymentMethod) {
        return new Reservation(-1, nicHandleId, domainName, durationMonths, new Date(), priceWithVat, true, false, null, null, transactionId, OperationType.RENEWAL, paymentMethod, null, null, null, true);
    }
    

    public static Reservation recreatedInstanceForTicket(String nicHandleId, String domainName, int durationMonths, PriceWithVat priceWithVat, Long ticketId, long transactionId, OperationType operationType, PaymentMethod paymentMethod, boolean readyForSettlement) {
        return new Reservation(-1, nicHandleId, domainName, durationMonths, new Date(), priceWithVat, readyForSettlement ,false, null, ticketId, transactionId, operationType, paymentMethod, null, null, null, false);
    }


    public Reservation(long id, String nicHandleId, String domainName, int durationMonths, Date creationDate, PriceWithVat priceWithVat, boolean readyForSettlement, boolean settled, Date settledDate, Long ticketId, Long transactionId, OperationType operationType, PaymentMethod paymentMethod, String invoiceNumber, String orderId, Integer ticketFinancialStatus, boolean domainExists) {
        //id is generated by db
        this.id = id;
        this.nicHandleId = nicHandleId;
        this.domainName = domainName;
        this.durationMonths = durationMonths;
        this.creationDate = creationDate;
        this.priceWithVat = priceWithVat;
        this.readyForSettlement = readyForSettlement;
        this.settled = settled;
        this.settledDate = settledDate;
        this.ticketId = ticketId;
        this.transactionId = transactionId;
        this.operationType = operationType;
        this.paymentMethod = paymentMethod;
        this.invoiceNumber = invoiceNumber;
        this.orderId = orderId;
        this.ticketFinancialStatus = ticketFinancialStatus;
        this.domainExists = domainExists;
    }

    public void markSettled(Date settledDate) {
        if (!settled) {
            settled = true;
            this.settledDate = settledDate;
        }
    }

    public void setReadyForSettlement(boolean readyForSettlement) {
        this.readyForSettlement = readyForSettlement;
    }

    public long getId() {
        return id;
    }

    public String getNicHandleId() {
        return nicHandleId;
    }

    public String getDomainName() {
        return domainName;
    }

    public int getDurationMonths() {
        return durationMonths;
    }

    public Date getCreationDate() {
        return creationDate;
    }

    public String getProductCode() {
        return priceWithVat.getProductCode();
    }

    public BigDecimal getNetAmount() {
        return priceWithVat.getNetAmount();
    }

    public int getVatId() {
        return priceWithVat.getVat().getId();
    }

    public String getVatCategory() {
        return priceWithVat.getVat().getCategory();
    }

    public double getVatRate() {
        return priceWithVat.getVat().getVatRate();
    }

    public BigDecimal getVatAmount() {
        return priceWithVat.getVatAmount();
    }

    public BigDecimal getTotal() {
        return priceWithVat.getTotal();
    }

    public boolean isReadyForSettlement() {
        return readyForSettlement;
    }

    public boolean isSettled() {
        return settled;
    }

    public Date getSettledDate() {
        return settledDate;
    }

    public Long getTicketId() {
        return ticketId;
    }

    public Long getTransactionId() {
        return transactionId;
    }

    public OperationType getOperationType() {
        return operationType;
    }

    public Date getStartDate() {
		return startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	/**
	 * Reservation end date (domain renewal date)
	 * @return
	 */
	public Date getEndDate() {
		return endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

    public String getInvoiceNumber() {
        return invoiceNumber;
    }

	@Override
    public String toString() {
        return String.format("Reservation[id: %s, nicHandleId: %s, domainName: %s, netAmount: %s, vatAmount: %s, readyForSettlement: %s, settled: %s, period.start: %s, period.end: %s]",
                id, nicHandleId, domainName, priceWithVat.getNetAmount(), priceWithVat.getVatAmount(), readyForSettlement, settled, startDate, endDate);
    }

    public PaymentMethod getPaymentMethod() {
    	return paymentMethod;
    }

    public String getOrderId() {
        return orderId;
    }

    public Integer getTicketFinancialStatus() {
        return ticketFinancialStatus;
    }

	public boolean getDomainExists() {
		return domainExists;
	}
}
