GRANT USAGE ON *.* TO 'crsuser_ws'@'%';
GRANT USAGE ON *.* TO 'crsuser_web'@'%';
GRANT USAGE ON *.* TO 'crsuser_sched'@'%';
GRANT USAGE ON *.* TO 'crsuser_api'@'%';
DROP USER 'crsuser_ws'@'%';
DROP USER 'crsuser_web'@'%';
DROP USER 'crsuser_sched'@'%';
DROP USER 'crsuser_api'@'%';

GRANT USAGE ON *.* TO 'crsuser_ws'@'%' IDENTIFIED BY PASSWORD '*AE61255AAC8EE41D576AAE31A532A34EE1EEB019';
GRANT USAGE ON *.* TO 'crsuser_web'@'%' IDENTIFIED BY PASSWORD '*AE61255AAC8EE41D576AAE31A532A34EE1EEB019';
GRANT USAGE ON *.* TO 'crsuser_sched'@'%' IDENTIFIED BY PASSWORD '*AE61255AAC8EE41D576AAE31A532A34EE1EEB019';
GRANT USAGE ON *.* TO 'crsuser_api'@'%' IDENTIFIED BY PASSWORD '*AE61255AAC8EE41D576AAE31A532A34EE1EEB019';

GRANT DELETE, INSERT, SELECT ON `crsdb`.`PersistedCommands` TO 'crsuser_api'@'%';
GRANT DELETE, INSERT, SELECT ON `crsdb`.`ResellerDefaultNameservers` TO 'crsuser_api'@'%';
GRANT DELETE, INSERT, SELECT ON `crsdb`.`Telecom` TO 'crsuser_api'@'%';
GRANT DELETE, INSERT, SELECT ON `crsdb`.`TicketNameserver` TO 'crsuser_api'@'%';
GRANT DELETE, INSERT, SELECT, UPDATE ON `crsdb`.`Contact` TO 'crsuser_api'@'%';
GRANT DELETE, INSERT, SELECT, UPDATE ON `crsdb`.`DNS` TO 'crsuser_api'@'%';
GRANT DELETE, INSERT, SELECT, UPDATE ON `crsdb`.`Payment` TO 'crsuser_api'@'%';
GRANT DELETE, INSERT, SELECT, UPDATE ON `crsdb`.`Reseller_Defaults` TO 'crsuser_api'@'%';
GRANT INSERT ON `crsdb`.`AccountVersionIndex` TO 'crsuser_api'@'%';
GRANT INSERT ON `crsdb`.`DoaVersionIndex` TO 'crsuser_api'@'%';
GRANT INSERT ON `crsdb`.`ReservationIndex` TO 'crsuser_api'@'%';
GRANT INSERT ON `crsdb`.`TicketIndex` TO 'crsuser_api'@'%';
GRANT INSERT ON `crsdb`.`TransactionIndex` TO 'crsuser_api'@'%';
GRANT INSERT, SELECT ON `crsdb`.`AccessHist` TO 'crsuser_api'@'%';
GRANT INSERT, SELECT ON `crsdb`.`ContactHist` TO 'crsuser_api'@'%';
GRANT INSERT, SELECT ON `crsdb`.`DNSHist` TO 'crsuser_api'@'%';
GRANT INSERT, SELECT ON `crsdb`.`DNS_Check_Notification_Date` TO 'crsuser_api'@'%';
GRANT INSERT, SELECT ON `crsdb`.`DNS_Check_Notification` TO 'crsuser_api'@'%';
GRANT INSERT, SELECT ON `crsdb`.`DepositHist` TO 'crsuser_api'@'%';
GRANT INSERT, SELECT ON `crsdb`.`DomainHist` TO 'crsuser_api'@'%';
GRANT INSERT, SELECT ON `crsdb`.`LoginAttemptFailure` TO 'crsuser_api'@'%';
GRANT INSERT, SELECT ON `crsdb`.`NicHandleHist` TO 'crsuser_api'@'%';
GRANT INSERT, SELECT ON `crsdb`.`TelecomHist` TO 'crsuser_api'@'%';
GRANT INSERT, SELECT ON `crsdb`.`TicketHist` TO 'crsuser_api'@'%';
GRANT INSERT, SELECT ON `crsdb`.`TicketNameserverHist` TO 'crsuser_api'@'%';
GRANT INSERT, SELECT ON `crsdb`.`TransactionHist` TO 'crsuser_api'@'%';
GRANT INSERT, SELECT ON `crsdb`.`login_attempts` TO 'crsuser_api'@'%';
GRANT INSERT, SELECT, UPDATE ON `crsdb`.`Access` TO 'crsuser_api'@'%';
GRANT INSERT, SELECT, UPDATE ON `crsdb`.`Deposit` TO 'crsuser_api'@'%';
GRANT INSERT, SELECT, UPDATE ON `crsdb`.`Domain` TO 'crsuser_api'@'%';
GRANT INSERT, SELECT, UPDATE ON `crsdb`.`NicHandle` TO 'crsuser_api'@'%';
GRANT INSERT, SELECT, UPDATE ON `crsdb`.`Reservation` TO 'crsuser_api'@'%';
GRANT INSERT, SELECT, UPDATE ON `crsdb`.`Ticket` TO 'crsuser_api'@'%';
GRANT INSERT, SELECT, UPDATE ON `crsdb`.`Transaction` TO 'crsuser_api'@'%';
GRANT LOCK TABLES ON `crsdb`.* TO 'crsuser_api'@'%';
-- GRANT SELECT ON `mysql`.`inventory` TO 'crsuser_api'@'%';
GRANT SELECT ON `crsdb`.`AccountFlags` TO 'crsuser_api'@'%';
GRANT SELECT ON `crsdb`.`App_Config` TO 'crsuser_api'@'%';
GRANT SELECT ON `crsdb`.`CategoryPermission` TO 'crsuser_api'@'%';
GRANT SELECT ON `crsdb`.`Category` TO 'crsuser_api'@'%';
GRANT SELECT ON `crsdb`.`Class_Category_Permission` TO 'crsuser_api'@'%';
GRANT SELECT ON `crsdb`.`Class_to_Category` TO 'crsuser_api'@'%';
GRANT SELECT ON `crsdb`.`Class` TO 'crsuser_api'@'%';
GRANT SELECT ON `crsdb`.`Counties` TO 'crsuser_api'@'%';
GRANT SELECT ON `crsdb`.`Countries` TO 'crsuser_api'@'%';
GRANT SELECT ON `crsdb`.`DSM_Action` TO 'crsuser_api'@'%';
GRANT SELECT ON `crsdb`.`DSM_Event` TO 'crsuser_api'@'%';
GRANT SELECT ON `crsdb`.`DSM_State` TO 'crsuser_api'@'%';
GRANT SELECT ON `crsdb`.`DSM_Transition_Action` TO 'crsuser_api'@'%';
GRANT SELECT ON `crsdb`.`DSM_Transition` TO 'crsuser_api'@'%';
GRANT SELECT ON `crsdb`.`EmailDisabler` TO 'crsuser_api'@'%';
GRANT SELECT ON `crsdb`.`EmailGroup` TO 'crsuser_api'@'%';
GRANT SELECT ON `crsdb`.`Email` TO 'crsuser_api'@'%';
GRANT SELECT ON `crsdb`.`INCOMING_DOC_DOMAINS` TO 'crsuser_api'@'%';
GRANT SELECT ON `crsdb`.`INCOMING_DOC` TO 'crsuser_api'@'%';
GRANT SELECT ON `crsdb`.`Invoice` TO 'crsuser_api'@'%';
GRANT SELECT ON `crsdb`.`Product` TO 'crsuser_api'@'%';
GRANT SELECT ON `crsdb`.`ReservationHist` TO 'crsuser_api'@'%';
GRANT SELECT ON `crsdb`.`StaticTableName` TO 'crsuser_api'@'%';
GRANT SELECT ON `crsdb`.`TicketAdminStatus` TO 'crsuser_api'@'%';
GRANT SELECT ON `crsdb`.`TicketFailCd` TO 'crsuser_api'@'%';
GRANT SELECT ON `crsdb`.`TicketTechStatus` TO 'crsuser_api'@'%';
GRANT SELECT ON `crsdb`.`TransfersHist` TO 'crsuser_api'@'%';
GRANT SELECT ON `crsdb`.`UserPermissions` TO 'crsuser_api'@'%';
GRANT SELECT ON `crsdb`.`Vat` TO 'crsuser_api'@'%';
GRANT SELECT ON `crsdb`.`Zone_Published` TO 'crsuser_api'@'%';
GRANT SELECT ON `crsdb`.`vat_category` TO 'crsuser_api'@'%';
GRANT SELECT, UPDATE ON `crsdb`.`Account` TO 'crsuser_api'@'%';
GRANT SELECT, UPDATE ON `crsdb`.`nicHandleSeq` TO 'crsuser_api'@'%';
-- Grants for 'crsuser_sched'@'%'
GRANT DELETE, INSERT, SELECT ON `crsdb`.`Telecom` TO 'crsuser_sched'@'%';
GRANT DELETE, INSERT, SELECT ON `crsdb`.`TicketNameserver` TO 'crsuser_sched'@'%';
GRANT DELETE, INSERT, SELECT, UPDATE ON `crsdb`.`Contact` TO 'crsuser_sched'@'%';
GRANT DELETE, INSERT, SELECT, UPDATE ON `crsdb`.`DNS_Check_Notification_Date` TO 'crsuser_sched'@'%';
GRANT DELETE, INSERT, SELECT, UPDATE ON `crsdb`.`DNS_Check_Notification` TO 'crsuser_sched'@'%';
GRANT DELETE, INSERT, SELECT, UPDATE ON `crsdb`.`DNS` TO 'crsuser_sched'@'%';
GRANT DELETE, INSERT, SELECT, UPDATE ON `crsdb`.`Domain` TO 'crsuser_sched'@'%';
GRANT DELETE, INSERT, SELECT, UPDATE ON `crsdb`.`Reservation` TO 'crsuser_sched'@'%';
GRANT DELETE, INSERT, SELECT, UPDATE ON `crsdb`.`SchedulerJob` TO 'crsuser_sched'@'%';
GRANT DELETE, INSERT, SELECT, UPDATE ON `crsdb`.`Transaction` TO 'crsuser_sched'@'%';
GRANT DELETE, SELECT ON `crsdb`.`Access` TO 'crsuser_sched'@'%';
GRANT DELETE, SELECT ON `crsdb`.`NicHandle` TO 'crsuser_sched'@'%';
GRANT DELETE, SELECT, UPDATE ON `crsdb`.`Ticket` TO 'crsuser_sched'@'%';
GRANT INSERT ON `crsdb`.`DeleteListHist` TO 'crsuser_sched'@'%';
GRANT INSERT ON `crsdb`.`ReservationIndex` TO 'crsuser_sched'@'%';
GRANT INSERT ON `crsdb`.`SchedulerJobHist` TO 'crsuser_sched'@'%';
GRANT INSERT ON `crsdb`.`TransactionIndex` TO 'crsuser_sched'@'%';
GRANT INSERT, SELECT ON `crsdb`.`AccessHist` TO 'crsuser_sched'@'%';
GRANT INSERT, SELECT ON `crsdb`.`ContactHist` TO 'crsuser_sched'@'%';
GRANT INSERT, SELECT ON `crsdb`.`DNSHist` TO 'crsuser_sched'@'%';
GRANT INSERT, SELECT ON `crsdb`.`DepositHist` TO 'crsuser_sched'@'%';
GRANT INSERT, SELECT ON `crsdb`.`DomainHist` TO 'crsuser_sched'@'%';
GRANT INSERT, SELECT ON `crsdb`.`Domain_Notifications` TO 'crsuser_sched'@'%';
GRANT INSERT, SELECT ON `crsdb`.`NicHandleHist` TO 'crsuser_sched'@'%';
GRANT INSERT, SELECT ON `crsdb`.`ReservationHist` TO 'crsuser_sched'@'%';
GRANT INSERT, SELECT ON `crsdb`.`TelecomHist` TO 'crsuser_sched'@'%';
GRANT INSERT, SELECT ON `crsdb`.`TicketHist` TO 'crsuser_sched'@'%';
GRANT INSERT, SELECT ON `crsdb`.`TicketNameserverHist` TO 'crsuser_sched'@'%';
GRANT INSERT, SELECT ON `crsdb`.`TransactionHist` TO 'crsuser_sched'@'%';
GRANT INSERT, SELECT ON `crsdb`.`TransfersHist` TO 'crsuser_sched'@'%';
GRANT INSERT, SELECT ON `crsdb`.`login_attempts` TO 'crsuser_sched'@'%';
GRANT INSERT, SELECT, UPDATE ON `crsdb`.`Deposit` TO 'crsuser_sched'@'%';
GRANT INSERT, SELECT, UPDATE ON `crsdb`.`Invoice` TO 'crsuser_sched'@'%';
GRANT INSERT, SELECT, UPDATE ON `crsdb`.`LastInvoiceNumber` TO 'crsuser_sched'@'%';
GRANT LOCK TABLES ON `crsdb`.* TO 'crsuser_sched'@'%';
-- GRANT SELECT ON `mysql`.`inventory` TO 'crsuser_sched'@'%';
GRANT SELECT ON `crsdb`.`AccountFlags` TO 'crsuser_sched'@'%';
GRANT SELECT ON `crsdb`.`Account` TO 'crsuser_sched'@'%';
GRANT SELECT ON `crsdb`.`App_Config` TO 'crsuser_sched'@'%';
GRANT SELECT ON `crsdb`.`CategoryPermission` TO 'crsuser_sched'@'%';
GRANT SELECT ON `crsdb`.`Category` TO 'crsuser_sched'@'%';
GRANT SELECT ON `crsdb`.`Class_Category_Permission` TO 'crsuser_sched'@'%';
GRANT SELECT ON `crsdb`.`Class_to_Category` TO 'crsuser_sched'@'%';
GRANT SELECT ON `crsdb`.`Class` TO 'crsuser_sched'@'%';
GRANT SELECT ON `crsdb`.`Counties` TO 'crsuser_sched'@'%';
GRANT SELECT ON `crsdb`.`Countries` TO 'crsuser_sched'@'%';
GRANT SELECT ON `crsdb`.`DSM_Action` TO 'crsuser_sched'@'%';
GRANT SELECT ON `crsdb`.`DSM_Event` TO 'crsuser_sched'@'%';
GRANT SELECT ON `crsdb`.`DSM_State` TO 'crsuser_sched'@'%';
GRANT SELECT ON `crsdb`.`DSM_Transition_Action` TO 'crsuser_sched'@'%';
GRANT SELECT ON `crsdb`.`DSM_Transition` TO 'crsuser_sched'@'%';
GRANT SELECT ON `crsdb`.`EmailDisabler` TO 'crsuser_sched'@'%';
GRANT SELECT ON `crsdb`.`EmailGroup` TO 'crsuser_sched'@'%';
GRANT SELECT ON `crsdb`.`Email` TO 'crsuser_sched'@'%';
GRANT SELECT ON `crsdb`.`INCOMING_DOC_DOMAINS` TO 'crsuser_sched'@'%';
GRANT SELECT ON `crsdb`.`INCOMING_DOC` TO 'crsuser_sched'@'%';
GRANT SELECT ON `crsdb`.`Payment` TO 'crsuser_sched'@'%';
GRANT SELECT ON `crsdb`.`Product` TO 'crsuser_sched'@'%';
GRANT SELECT ON `crsdb`.`ResellerDefaultNameservers` TO 'crsuser_sched'@'%';
GRANT SELECT ON `crsdb`.`Reseller_Defaults` TO 'crsuser_sched'@'%';
GRANT SELECT ON `crsdb`.`StaticTableName` TO 'crsuser_sched'@'%';
GRANT SELECT ON `crsdb`.`TicketAdminStatus` TO 'crsuser_sched'@'%';
GRANT SELECT ON `crsdb`.`TicketFailCd` TO 'crsuser_sched'@'%';
GRANT SELECT ON `crsdb`.`TicketTechStatus` TO 'crsuser_sched'@'%';
GRANT SELECT ON `crsdb`.`UserPermissions` TO 'crsuser_sched'@'%';
GRANT SELECT ON `crsdb`.`Vat` TO 'crsuser_sched'@'%';
GRANT SELECT ON `crsdb`.`Zone_Published` TO 'crsuser_sched'@'%';
GRANT SELECT ON `crsdb`.`vat_category` TO 'crsuser_sched'@'%';
GRANT SELECT, UPDATE ON `crsdb`.`SchedulerConfig` TO 'crsuser_sched'@'%';
GRANT UPDATE ON `crsdb`.`nicHandleSeq` TO 'crsuser_sched'@'%';
-- Grants for 'crsuser_web'@'%'
GRANT DELETE, INSERT, SELECT ON `crsdb`.`DNS_Check_Notification` TO 'crsuser_web'@'%';
GRANT DELETE, INSERT, SELECT ON `crsdb`.`ResellerDefaultNameservers` TO 'crsuser_web'@'%';
GRANT DELETE, INSERT, SELECT ON `crsdb`.`ResetPass` TO 'crsuser_web'@'%';
GRANT DELETE, INSERT, SELECT ON `crsdb`.`Telecom` TO 'crsuser_web'@'%';
GRANT DELETE, INSERT, SELECT ON `crsdb`.`TicketNameserver` TO 'crsuser_web'@'%';
GRANT DELETE, INSERT, SELECT, UPDATE ON `crsdb`.`Bulk_Transfer_Domain` TO 'crsuser_web'@'%';
GRANT DELETE, INSERT, SELECT, UPDATE ON `crsdb`.`Contact` TO 'crsuser_web'@'%';
GRANT DELETE, INSERT, SELECT, UPDATE ON `crsdb`.`DNS` TO 'crsuser_web'@'%';
GRANT DELETE, INSERT, SELECT, UPDATE ON `crsdb`.`EmailGroup` TO 'crsuser_web'@'%';
GRANT DELETE, INSERT, SELECT, UPDATE ON `crsdb`.`INCOMING_DOC_DOMAINS` TO 'crsuser_web'@'%';
GRANT DELETE, INSERT, SELECT, UPDATE ON `crsdb`.`INCOMING_DOC` TO 'crsuser_web'@'%';
GRANT DELETE, INSERT, SELECT, UPDATE ON `crsdb`.`Payment` TO 'crsuser_web'@'%';
GRANT DELETE, INSERT, SELECT, UPDATE ON `crsdb`.`Product` TO 'crsuser_web'@'%';
GRANT DELETE, INSERT, SELECT, UPDATE ON `crsdb`.`Reseller_Defaults` TO 'crsuser_web'@'%';
GRANT DELETE, INSERT, SELECT, UPDATE ON `crsdb`.`SchedulerConfig` TO 'crsuser_web'@'%';
GRANT DELETE, INSERT, SELECT, UPDATE ON `crsdb`.`TicketResponse` TO 'crsuser_web'@'%';
GRANT DELETE, INSERT, SELECT, UPDATE ON `crsdb`.`UserPermissions` TO 'crsuser_web'@'%';
GRANT DELETE, INSERT, SELECT, UPDATE ON `crsdb`.`Vat` TO 'crsuser_web'@'%';
GRANT DELETE, SELECT, UPDATE ON `crsdb`.`Ticket` TO 'crsuser_web'@'%';
GRANT INSERT ON `crsdb`.`AccountVersionIndex` TO 'crsuser_web'@'%';
GRANT INSERT ON `crsdb`.`DoaVersionIndex` TO 'crsuser_web'@'%';
GRANT INSERT ON `crsdb`.`ReservationIndex` TO 'crsuser_web'@'%';
GRANT INSERT ON `crsdb`.`TransactionIndex` TO 'crsuser_web'@'%';
GRANT INSERT, SELECT ON `crsdb`.`AccessHist` TO 'crsuser_web'@'%';
GRANT INSERT, SELECT ON `crsdb`.`AccountFlagsHist` TO 'crsuser_web'@'%';
GRANT INSERT, SELECT ON `crsdb`.`AccountHist` TO 'crsuser_web'@'%';
GRANT INSERT, SELECT ON `crsdb`.`ContactHist` TO 'crsuser_web'@'%';
GRANT INSERT, SELECT ON `crsdb`.`DNSHist` TO 'crsuser_web'@'%';
GRANT INSERT, SELECT ON `crsdb`.`DNS_Check_Notification_Date` TO 'crsuser_web'@'%';
GRANT INSERT, SELECT ON `crsdb`.`DepositHist` TO 'crsuser_web'@'%';
GRANT INSERT, SELECT ON `crsdb`.`DomainHist` TO 'crsuser_web'@'%';
GRANT INSERT, SELECT ON `crsdb`.`EmailDisablerHist` TO 'crsuser_web'@'%';
GRANT INSERT, SELECT ON `crsdb`.`EmailGroupHist` TO 'crsuser_web'@'%';
GRANT INSERT, SELECT ON `crsdb`.`EmailHist` TO 'crsuser_web'@'%';
GRANT INSERT, SELECT ON `crsdb`.`LoginAttemptFailure` TO 'crsuser_web'@'%';
GRANT INSERT, SELECT ON `crsdb`.`NicHandleHist` TO 'crsuser_web'@'%';
GRANT INSERT, SELECT ON `crsdb`.`TelecomHist` TO 'crsuser_web'@'%';
GRANT INSERT, SELECT ON `crsdb`.`TicketHist` TO 'crsuser_web'@'%';
GRANT INSERT, SELECT ON `crsdb`.`TicketNameserverHist` TO 'crsuser_web'@'%';
GRANT INSERT, SELECT ON `crsdb`.`TransfersHist` TO 'crsuser_web'@'%';
GRANT INSERT, SELECT ON `crsdb`.`login_attempts` TO 'crsuser_web'@'%';
GRANT INSERT, SELECT, UPDATE ON `crsdb`.`Access` TO 'crsuser_web'@'%';
GRANT INSERT, SELECT, UPDATE ON `crsdb`.`AccountFlags` TO 'crsuser_web'@'%';
GRANT INSERT, SELECT, UPDATE ON `crsdb`.`Account` TO 'crsuser_web'@'%';
GRANT INSERT, SELECT, UPDATE ON `crsdb`.`App_Config` TO 'crsuser_web'@'%';
GRANT INSERT, SELECT, UPDATE ON `crsdb`.`Bulk_Transfer` TO 'crsuser_web'@'%';
GRANT INSERT, SELECT, UPDATE ON `crsdb`.`Deposit` TO 'crsuser_web'@'%';
GRANT INSERT, SELECT, UPDATE ON `crsdb`.`Domain` TO 'crsuser_web'@'%';
GRANT INSERT, SELECT, UPDATE ON `crsdb`.`EmailDisabler` TO 'crsuser_web'@'%';
GRANT INSERT, SELECT, UPDATE ON `crsdb`.`NicHandle` TO 'crsuser_web'@'%';
GRANT INSERT, SELECT, UPDATE ON `crsdb`.`Reservation` TO 'crsuser_web'@'%';
GRANT INSERT, SELECT, UPDATE ON `crsdb`.`Transaction` TO 'crsuser_web'@'%';
GRANT LOCK TABLES ON `crsdb`.* TO 'crsuser_web'@'%';
-- GRANT SELECT ON `mysql`.`inventory` TO 'crsuser_web'@'%';
GRANT SELECT ON `crsdb`.`CategoryPermission` TO 'crsuser_web'@'%';
GRANT SELECT ON `crsdb`.`Category` TO 'crsuser_web'@'%';
GRANT SELECT ON `crsdb`.`Class_Category_Permission` TO 'crsuser_web'@'%';
GRANT SELECT ON `crsdb`.`Class_to_Category` TO 'crsuser_web'@'%';
GRANT SELECT ON `crsdb`.`Class` TO 'crsuser_web'@'%';
GRANT SELECT ON `crsdb`.`Counties` TO 'crsuser_web'@'%';
GRANT SELECT ON `crsdb`.`Countries` TO 'crsuser_web'@'%';
GRANT SELECT ON `crsdb`.`DSM_Action` TO 'crsuser_web'@'%';
GRANT SELECT ON `crsdb`.`DSM_Event` TO 'crsuser_web'@'%';
GRANT SELECT ON `crsdb`.`DSM_State` TO 'crsuser_web'@'%';
GRANT SELECT ON `crsdb`.`DSM_Transition_Action` TO 'crsuser_web'@'%';
GRANT SELECT ON `crsdb`.`DSM_Transition` TO 'crsuser_web'@'%';
GRANT SELECT ON `crsdb`.`Invoice` TO 'crsuser_web'@'%';
GRANT SELECT ON `crsdb`.`PaymentHist` TO 'crsuser_web'@'%';
GRANT SELECT ON `crsdb`.`ReservationHist` TO 'crsuser_web'@'%';
GRANT SELECT ON `crsdb`.`SchedulerJobHist` TO 'crsuser_web'@'%';
GRANT SELECT ON `crsdb`.`SchedulerJob` TO 'crsuser_web'@'%';
GRANT SELECT ON `crsdb`.`StaticTableName` TO 'crsuser_web'@'%';
GRANT SELECT ON `crsdb`.`TicketAdminStatus` TO 'crsuser_web'@'%';
GRANT SELECT ON `crsdb`.`TicketFailCd` TO 'crsuser_web'@'%';
GRANT SELECT ON `crsdb`.`TicketTechStatus` TO 'crsuser_web'@'%';
GRANT SELECT ON `crsdb`.`TransactionHist` TO 'crsuser_web'@'%';
GRANT SELECT ON `crsdb`.`Zone_Published` TO 'crsuser_web'@'%';
GRANT SELECT ON `crsdb`.`vat_category` TO 'crsuser_web'@'%';
GRANT SELECT, UPDATE ON `crsdb`.`Email` TO 'crsuser_web'@'%';
GRANT SELECT, UPDATE ON `crsdb`.`nicHandleSeq` TO 'crsuser_web'@'%';
-- Grants for 'crsuser_ws'@'%'
GRANT DELETE, INSERT, SELECT ON `crsdb`.`ResellerDefaultNameservers` TO 'crsuser_ws'@'%';
GRANT DELETE, INSERT, SELECT ON `crsdb`.`Telecom` TO 'crsuser_ws'@'%';
GRANT DELETE, INSERT, SELECT ON `crsdb`.`TicketNameserver` TO 'crsuser_ws'@'%';
GRANT DELETE, INSERT, SELECT, UPDATE ON `crsdb`.`Contact` TO 'crsuser_ws'@'%';
GRANT DELETE, INSERT, SELECT, UPDATE ON `crsdb`.`DNS` TO 'crsuser_ws'@'%';
GRANT DELETE, INSERT, SELECT, UPDATE ON `crsdb`.`Payment` TO 'crsuser_ws'@'%';
GRANT DELETE, INSERT, SELECT, UPDATE ON `crsdb`.`Reseller_Defaults` TO 'crsuser_ws'@'%';
GRANT DELETE, INSERT, SELECT, UPDATE ON `crsdb`.`Reservation` TO 'crsuser_ws'@'%';
GRANT DELETE, INSERT, SELECT, UPDATE ON `crsdb`.`ResetPass` TO 'crsuser_ws'@'%';
GRANT DELETE, INSERT, SELECT, UPDATE ON `crsdb`.`Transaction` TO 'crsuser_ws'@'%';
GRANT INSERT ON `crsdb`.`AccountVersionIndex` TO 'crsuser_ws'@'%';
GRANT INSERT ON `crsdb`.`DoaVersionIndex` TO 'crsuser_ws'@'%';
GRANT INSERT ON `crsdb`.`PaymentHist` TO 'crsuser_ws'@'%';
GRANT INSERT ON `crsdb`.`ReservationIndex` TO 'crsuser_ws'@'%';
GRANT INSERT ON `crsdb`.`TicketIndex` TO 'crsuser_ws'@'%';
GRANT INSERT ON `crsdb`.`TransactionIndex` TO 'crsuser_ws'@'%';
GRANT INSERT, SELECT ON `crsdb`.`AccessHist` TO 'crsuser_ws'@'%';
GRANT INSERT, SELECT ON `crsdb`.`ContactHist` TO 'crsuser_ws'@'%';
GRANT INSERT, SELECT ON `crsdb`.`DNSHist` TO 'crsuser_ws'@'%';
GRANT INSERT, SELECT ON `crsdb`.`DNS_Check_Notification_Date` TO 'crsuser_ws'@'%';
GRANT INSERT, SELECT ON `crsdb`.`DNS_Check_Notification` TO 'crsuser_ws'@'%';
GRANT INSERT, SELECT ON `crsdb`.`DepositHist` TO 'crsuser_ws'@'%';
GRANT INSERT, SELECT ON `crsdb`.`DomainHist` TO 'crsuser_ws'@'%';
GRANT INSERT, SELECT ON `crsdb`.`EmailDisablerHist` TO 'crsuser_ws'@'%';
GRANT INSERT, SELECT ON `crsdb`.`LoginAttemptFailure` TO 'crsuser_ws'@'%';
GRANT INSERT, SELECT ON `crsdb`.`NicHandleHist` TO 'crsuser_ws'@'%';
GRANT INSERT, SELECT ON `crsdb`.`ReservationHist` TO 'crsuser_ws'@'%';
GRANT INSERT, SELECT ON `crsdb`.`TelecomHist` TO 'crsuser_ws'@'%';
GRANT INSERT, SELECT ON `crsdb`.`TicketHist` TO 'crsuser_ws'@'%';
GRANT INSERT, SELECT ON `crsdb`.`TicketNameserverHist` TO 'crsuser_ws'@'%';
GRANT INSERT, SELECT ON `crsdb`.`TransactionHist` TO 'crsuser_ws'@'%';
GRANT INSERT, SELECT ON `crsdb`.`Zone_Published` TO 'crsuser_ws'@'%';
GRANT INSERT, SELECT ON `crsdb`.`login_attempts` TO 'crsuser_ws'@'%';
GRANT INSERT, SELECT, UPDATE ON `crsdb`.`Access` TO 'crsuser_ws'@'%';
GRANT INSERT, SELECT, UPDATE ON `crsdb`.`Deposit` TO 'crsuser_ws'@'%';
GRANT INSERT, SELECT, UPDATE ON `crsdb`.`Domain` TO 'crsuser_ws'@'%';
GRANT INSERT, SELECT, UPDATE ON `crsdb`.`EmailDisabler` TO 'crsuser_ws'@'%';
GRANT INSERT, SELECT, UPDATE ON `crsdb`.`Invoice` TO 'crsuser_ws'@'%';
GRANT INSERT, SELECT, UPDATE ON `crsdb`.`NicHandle` TO 'crsuser_ws'@'%';
GRANT INSERT, SELECT, UPDATE ON `crsdb`.`Ticket` TO 'crsuser_ws'@'%';
GRANT LOCK TABLES ON `crsdb`.* TO 'crsuser_ws'@'%';
-- GRANT SELECT ON `mysql`.`inventory` TO 'crsuser_ws'@'%';
GRANT SELECT ON `crsdb`.`AccountFlagsHist` TO 'crsuser_ws'@'%';
GRANT SELECT ON `crsdb`.`AccountFlags` TO 'crsuser_ws'@'%';
GRANT SELECT ON `crsdb`.`Account` TO 'crsuser_ws'@'%';
GRANT SELECT ON `crsdb`.`App_Config` TO 'crsuser_ws'@'%';
GRANT SELECT ON `crsdb`.`CategoryPermission` TO 'crsuser_ws'@'%';
GRANT SELECT ON `crsdb`.`Category` TO 'crsuser_ws'@'%';
GRANT SELECT ON `crsdb`.`Class_Category_Permission` TO 'crsuser_ws'@'%';
GRANT SELECT ON `crsdb`.`Class_to_Category` TO 'crsuser_ws'@'%';
GRANT SELECT ON `crsdb`.`Class` TO 'crsuser_ws'@'%';
GRANT SELECT ON `crsdb`.`Counties` TO 'crsuser_ws'@'%';
GRANT SELECT ON `crsdb`.`Countries` TO 'crsuser_ws'@'%';
GRANT SELECT ON `crsdb`.`DSM_Action` TO 'crsuser_ws'@'%';
GRANT SELECT ON `crsdb`.`DSM_Event` TO 'crsuser_ws'@'%';
GRANT SELECT ON `crsdb`.`DSM_State` TO 'crsuser_ws'@'%';
GRANT SELECT ON `crsdb`.`DSM_Transition_Action` TO 'crsuser_ws'@'%';
GRANT SELECT ON `crsdb`.`DSM_Transition` TO 'crsuser_ws'@'%';
GRANT SELECT ON `crsdb`.`EmailGroup` TO 'crsuser_ws'@'%';
GRANT SELECT ON `crsdb`.`Email` TO 'crsuser_ws'@'%';
GRANT SELECT ON `crsdb`.`INCOMING_DOC_DOMAINS` TO 'crsuser_ws'@'%';
GRANT SELECT ON `crsdb`.`INCOMING_DOC` TO 'crsuser_ws'@'%';
GRANT SELECT ON `crsdb`.`Product` TO 'crsuser_ws'@'%';
GRANT SELECT ON `crsdb`.`StaticTableName` TO 'crsuser_ws'@'%';
GRANT SELECT ON `crsdb`.`TicketAdminStatus` TO 'crsuser_ws'@'%';
GRANT SELECT ON `crsdb`.`TicketFailCd` TO 'crsuser_ws'@'%';
GRANT SELECT ON `crsdb`.`TicketTechStatus` TO 'crsuser_ws'@'%';
GRANT SELECT ON `crsdb`.`TransfersHist` TO 'crsuser_ws'@'%';
GRANT SELECT ON `crsdb`.`UserPermissions` TO 'crsuser_ws'@'%';
GRANT SELECT ON `crsdb`.`Vat` TO 'crsuser_ws'@'%';
GRANT SELECT ON `crsdb`.`vat_category` TO 'crsuser_ws'@'%';
GRANT SELECT, UPDATE ON `crsdb`.`LastInvoiceNumber` TO 'crsuser_ws'@'%';
GRANT SELECT, UPDATE ON `crsdb`.`nicHandleSeq` TO 'crsuser_ws'@'%';
